UI/Controllers/ManagementController.cs
using Application.Services.Interface;
using Application.Services.Interfaces;
using Application.ViewModels;
using Application.ViewModels.Error;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using System.Reflection;
using System.Text.Json.Serialization;
using UI.Models.ActionsFilter;

namespace UI.Controllers
{
    [AuthorizeToken]
    [AllowAnonymous]
    public class ManagementController : Controller
    {
        private readonly InterCameraService _interCalibrationService;
        private readonly InterConfigurationService _interConfigurationService;
        private readonly InterConfigureOptionsServices _configureOptionsServices;

        public List<vmPlc> vmPlcs = [];

        public ManagementController(InterCameraService interCalibrationService, InterConfigurationService interConfigurationService, InterConfigureOptionsServices configureOptionsServices)
        {
            _interCalibrationService = interCalibrationService;
            _interConfigurationService = interConfigurationService;
            _configureOptionsServices = configureOptionsServices;
        }

        /// <summary>
        /// perform a connection test for the current connection
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> TestConnectionPlc()
        {
            try
            {
                bool plcConnection = false;
                plcConnection = await _interConfigurationService.TestConnectionPlc();
                return Ok(plcConnection);
            }
            catch (Exception e) { return BadRequest(new ErrorViewModel { Message = e.Message, Response = false }); }
        }

        /// <summary>
        /// Load a list for all tags saved
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        //[AuthorizeRoles("User", "Admin")]
        public async Task<IActionResult> TagList()
        {
            List<vmPlc>? listPlc = await _interConfigurationService.GetListPlc();
            vmPlcs = listPlc;
            return View(listPlc);
        }

        /// <summary>
        /// open one view for add new tag in list
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult AddTagInList()
        {
            ViewBag.ListTypeTag = new SelectList(new List<string> { "bool", "int", "double", });
            return PartialView("_AddTagInListPartial");
        }

        /// <summary>
        /// Add a new tag in list
        /// </summary>
        /// <param name="plc"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AddTagInList(vmPlc plc)
        {
            try
            {
                List<vmPlc> listPlc = [];

                if (plc.Type == "bool")
                    plc.Value = plc.Value == "1" ? "true" : "false";
                listPlc.Add(plc);

                bool resp = await _interConfigurationService.AddTagInList(listPlc);

                TempDataRequest(resp);
                return Redirect("TagList");
            }
            catch { return Redirect("TagList"); }
        }


        /// <summary>
        /// open a view for edit an existing tag
        /// </summary>
        /// <param name="idTag"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditTagInList(int idTag)
        {
            ViewBag.ListTypeTag = new SelectList(new List<string> { "bool", "int", "double", });

            vmPlc? item = await _interConfigurationService.DetailTagInList(idTag);

            if (item.Type == "bool")
                item.Value = item.Value.Equals("true") ? "1" : "0";

            return PartialView("_EditTagInListPartial", item);
        }

        /// <summary>
        /// edit an existing tag in the list
        /// </summary>
        /// <param name="plc"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> UpdateTagInList(vmPlc plc)
        {
            try
            {
                bool item = await _interConfigurationService.UpdateTagInList(plc);

                TempDataRequest(item);
                return Redirect("TagList");
            }
            catch { return BadRequest(plc); }
        }

        /// <summary>
        /// delete an existing tag in the list
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpDelete]
        public async Task<IActionResult> DeleteTagInList(int id)
        {
            try
            {
                bool item = await _interConfigurationService.DeleteTagInList(id);

                TempDataRequest(item);
                return item ? Ok(item) : BadRequest(item);
            }
            catch { return Redirect("TagList"); }
        }

        /// <summary>
        /// Opens a view of the last calibration performed and returns these values
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        //[AuthorizeRoles("Admin")]
        public async Task<IActionResult> Calibration()
        {

            try
            {
                var data = await _interCalibrationService.GetCalibrationCameraAsync();
                return View(data);
            }
            catch { return View(new vmCalibrationCamera()); }
        }

        /// <summary>
        /// Submit a request to perform a calibration
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        //[AuthorizeRoles("Admin")]
        public async Task<IActionResult> ExecuteCalibration()
        {
            try
            {
                await _interCalibrationService.ExecuteCalibration();
                return RedirectToAction("", "");
            }
            catch { return RedirectToAction("", ""); }
        }

        /// <summary>
        /// searches for a last performed calibration and return those values
        /// </summary>
        /// <returns></returns>
        //[AuthorizeRoles("User", "Admin")]
        [HttpGet]
        public async Task<IActionResult> GetCalibrationCamera()
        {
            try
            {
                var data = await _interCalibrationService.GetCalibrationCameraAsync();
                return Ok(data);
            }
            catch { return BadRequest(""); }
        }

        /// <summary>
        /// Play a camera antisway
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> VideoCamera()
        {
            try
            {
                //var data = await _interCalibrationService.GetVideoCameraAsync();
                return Ok();
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        //[AuthorizeRoles("User", "Admin")]
        public async Task<IActionResult> Monitoring()
        {
            var data = await _interCalibrationService.GetCalibrationCameraAsync();
            return View(data);
        }

        /// <summary>
        /// Open a view for Plc Settings
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> PlcSettings()
        {
            ViewBag.Driver = await _configureOptionsServices.GetDriversOptions();
            ViewBag.ListCpuType = await _configureOptionsServices.GetCpuTypesOptions();

            vmPlcSettings plcSetting = await _interConfigurationService.GetSettingsPlc();
            return View(plcSetting);
        }

        /// <summary>
        /// Set a new configuration for Plc
        /// </summary>
        /// <param name="plcSettings"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> PlcSettings(vmPlcSettings plcSettings)
        {
            try
            {
                bool plcSetting = await _interConfigurationService.UpdateSettingsPlc(plcSettings);
                TempDataRequest(plcSetting);

                return plcSetting ? Redirect("PlcSettings") : BadRequest(plcSetting);
            }
            catch { return BadRequest(false); }
        }

        /// <summary>
        /// Set a new alert message for all requisition's
        /// </summary>
        /// <param name="resp"></param>
        private void TempDataRequest(bool resp)
        {
            if (resp)
                TempData["SuccessMessage"] = "Successfully!";
            else
                TempData["ErrorMessage"] = "Error, not saved!";
        }

        private void TempDataErrorMessage(string message)
        {
            TempData["ErrorMessage"] = message.Trim();
        }

        /// <summary>
        /// Send a new value to tag
        /// </summary>
        /// <param name="vmWrite"></param>
        /// <returns></returns>
        //[HttpPost]
        //public async Task<IActionResult> SetValueToPlc(List<vmWritePlc> vmWrite)
        //{
        //    if (vmWrite == null || !vmWrite.Any())
        //        return BadRequest("No data received.");
        //    try
        //    {
        //        List<vmApiRequestWritePlc> vmApiRequest = [];
        //        foreach (var item in vmWrite)
        //        {
        //            var plcData = await _interConfigurationService.DetailTagInList(item.Id);
        //            vmApiRequest.Add(new vmApiRequestWritePlc
        //            {
        //                AddressPlc = plcData.AddressPlc,
        //                Type = item.Type,
        //                Value = item.Value,
        //            });
        //        }
        //        var resp = await _interConfigurationService.WritePlcAsync(vmApiRequest);

        //        if (resp)
        //            foreach (var item in vmWrite)

UI/Views/Management/Calibration.cshtml
@model Application.ViewModels.vmCalibrationCamera

@{
    Layout = "_Layout";
    ViewData["Title"] = "Calibration";
}

<style>
    .camera-container {
        height: 600px;
        border: 1px solid #ccc;
        background-color: #eee;
        display: flex;
        justify-content: center;
        align-items: center;
        margin-right: 20px;
        border-radius: 5px;
    }

    .camera {
        width: 80%;
        height: 80%;
        background-color: #aaa;
        border-radius: 5px;
    }

</style>

<div class="row">
    <div class="col-md-8">
        <div class="col-md-10">
            <div class="camera-container d-flex justify-content-center align-items-center">
                <div class="camera"></div>
            </div>
            <div class="card" style="background-color: #bdbcbc; margin-right:20px;">
                <div class="text-center">
                    <h4>X - Y</h4>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 mx-auto my-auto">
        <div class="row text-center">
            <h3>Delta</h3>
        </div>
        <form method="get" asp-action="ExecuteCalibration">
            <div class="row text-center">
                <div class="col-md-6 ">
                    <div class="form-group">
                        <img class="img" height="35px" src="~/imgs/deltax.png" title="X" />
                        <input asp-for="DeltaX" type="number" class="form-control" />
                        <span asp-validation-for="DeltaX" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6 ">
                    <div class="form-group">
                        <img class=" img" height="35px" src="~/imgs/deltay.png" title="Y" />
                        <input asp-for="DeltaY" type="number" class="form-control" />
                        <span asp-validation-for="DeltaY" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-6 mt-4">
                    <div class="form-group">
                        <label asp-for="DeltaZ" class="control-label">DELTA 1</label>
                        <input asp-for="DeltaZ" type="number" class="form-control" />
                        <span asp-validation-for="DeltaZ" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6 mt-4">
                    <div class="form-group">
                        <label asp-for="DeltaZZ" class="control-label">DELTA 2</label>
                        <input asp-for="DeltaZZ" type="number" class="form-control" />
                        <span asp-validation-for="DeltaZZ" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 mt-3 text-center">
                    <div class="form-group">
                        <input type="submit" class="btn btn-info btn-lg" value="Calibrar" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {

        });
    </script>
}

UI/Views/Management/Monitoring.cshtml
@model Application.ViewModels.vmCalibrationCamera

@{
    Layout = "_Layout";

    ViewData["Title"] = "Monitoring";

}
<style>
    .camera-container {
        height: 500px;
        border: 1px solid #ccc;
        background-color: #eee;
        display: flex;
        justify-content: center;
        align-items: center;
        margin-right: 20px;
        border-radius: 5px;
    }

    .camera {
        width: 100%;
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: #aaa;
        border-radius: 5px;
    }

        .camera img {
            max-width: 100%;
            max-height: 100%;
            object-fit: cover;
            border-radius: 5px;
        }

</style>

<div class="row">
    <div class="col-md-8">
        <div class="col-md-10">
            <div class="camera-container d-flex justify-content-center align-items-center">
                <div class="camera">
                    @* <video id="cameraFeed" src="" alt="Camera Feed" class="img-fluid"> *@
                </div>
            </div>
            <div class="card" style="background-color: #bdbcbc; margin-right:20px;">
                <div class="text-center">
                    <h4>X - Y</h4>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 mx-auto my-auto">
        <div class="row text-center">
            <h3>DELTA</h3>
        </div>
        <div class="row text-center">
            <div class="col-md-6 ">
                <div class="form-group">
                    <img class=" img" height="35px" src="~/imgs/deltax.png" title="X" />
                    <input asp-for="DeltaX" type="number" class="form-control" id="DeltaX" readonly />
                    <span asp-validation-for="DeltaX" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6 ">
                <div class="form-group">
                    <img class="img" height="35px" src="~/imgs/deltay.png" title="Y" />
                    <input asp-for="DeltaY" type="number" class="form-control" id="DeltaY" readonly />
                    <span asp-validation-for="DeltaY" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-6 mt-4">
                <div class="form-group">
                    <label asp-for="DeltaZ" class="control-label">other</label>
                    <input asp-for="DeltaZ" type="number" class="form-control" id="DeltaZ" readonly />
                    <span asp-validation-for="DeltaZ" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6 mt-4">
                <div class="form-group">
                    <label asp-for="DeltaZZ" class="control-label">other</label>
                    <input asp-for="DeltaZZ" type="number" class="form-control" id="DeltaZZ" readonly />
                    <span asp-validation-for="DeltaZZ" class="text-danger"></span>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {

            async function fetchCameraValues() {
                try {
                    const response = await fetch('@Url.Action("VideoCamera")');

                    if (!response.ok) {
                        const error = await response.text();
                        throw new Error(error);
                    }

                    const data = await response.json();
                    document.getElementById('cameraFeed').src = data.cameraFeedUrl;

                } catch (error) {
                    console.error('Error fetching Camera values: \n' + error);
                }
            }

            fetchCameraValues();
        });

    </script>
}

UI/Views/Management/TagList.cshtml
@model List<Application.ViewModels.vmPlc>

@{
    Layout = "_Layout";
    ViewData["Title"] = "Plc Communication";
}
<style>
    .edit-value {
        width: 100px;
    }

    .save-button {
        margin: 0;
    }

    .dataTables_wrapper .dataTables_length,
    .dataTables_wrapper .dataTables_filter {
        margin-bottom: 10px;
    }

    .dataTables_wrapper .dataTables_info {
        margin-top: 10px;
    }

    .card-header {
        background-color: gray;
        color: #fff;
    }

    .center-input {
        text-align: center;
    }

        .center-input input {
            margin: auto;
            display: block;
        }

 /*    .dt-layout-row{
        display: flex;
        justify-content: space-between;
    } */

</style>

<div class="container mt-5 mb-5">
    <div class="card">
        <div class="card-header text-center">
            <h2>Tag Communication</h2>
        </div>
        <div class="card-body">
            <div class="row mb-3">

                <div class="col-md-6">
                    <h2>Tag's</h2>
                </div>
                <div class="col-md-6 text-end">
                    <button class="btn btn-outline-info add-button">
                        <i class="fa fa-solid fa-plus"></i> Add new tag
                    </button>
                    <button class="btn btn-outline-warning get-updated-values">
                        <i class="fa fa-solid fa-rotate-right"></i> Update all tag values
                    </button>
                </div>
            </div>

            @if (Model.Count > 0)
            {
                <table id="plcTable" class="table table-striped table-responsive table-hover table-bordered  dt-responsive nowrap" style="width:100%">
                    <thead class="table-active">
                        <tr>
                            <th hidden>Id</th>
                            <th hidden>Address</th>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Last Value</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var plc in Model)
                        {
                            <tr>
                                <td hidden>@plc.Id</td>
                                <td hidden>@plc.AddressPlc</td>
                                <td width="48%">@plc.Name</td>
                                <td width="7%" class="text-center">@plc.Type</td>
                                <td width="15%" class="center-input">
                                    @{
                                        if (plc.Type == "bool")
                                        {
                                            int value = plc.Value.Equals("true") ? 1 : 0;
                                            <input type="number" class="form-control edit-value" min="0" max="1" step="1" onkeydown="return false;" value="@value" />
                                        }
                                        else if (plc.Type.Equals("int"))
                                        {
                                            <input type="number" class="form-control edit-value" min="0" max="9999999" step="1" onkeydown="return true;" value="@plc.Value" />
                                        }
                                        else if (plc.Type.Equals("double"))
                                        {
                                            <input type="number" class="form-control edit-value" min="0" max="9999999" step="0.1" onkeydown="return true;" value="@plc.Value" />
                                        }
                                    }
                                </td>

                                <td width="30%" class="text-center">
                                    <button class="btn btn-warning set-value-button" title="send a new value to tag"><i class="fa fa-solid fa-wrench"></i> Set value</button>
                                    <button class="btn btn-secondary details-button" title="edit tag in TagList"><i class="fa fa-solid fa-gear"></i> Edit tag</button>
                                    <button class="btn btn-danger delete-button" style="height: 38px;" title="delete tag in TagList"><i class="fa fa-solid fa-trash"></i> </button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="row">
                    <p class="text-center">Not Found Tags</p>
                    <div class="row col-md-3 mx-auto">
                        <button class="btn btn-info add-button">Add tag</button>
                    </div>
                </div>
            }

            <div class="modal" id="detailsModal" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header justify-content-between">
                            <h5 class="modal-title">Tag</h5>
                            <button type="button" class="btn-close" data-dismiss="modal" onclick="closeModal()" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <!---->
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" onclick="closeModal()" data-dismiss="modal">close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            var table = new DataTable('#plcTable', {
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/English.json",
                    "lengthMenu": "Show _MENU_ records per page",
                },
                "order": [[0, 'asc']],
                "fixedHeader": true,
                "pageLength": 15,
                "responsive": true
            });

            //update all tag values
            document.querySelector('.get-updated-values').addEventListener('click', async function () {
                try {
                    var listAddress = [];

                    document.querySelectorAll('#plcTable tbody tr').forEach(function (row) {
                        var address = row.querySelector('td:nth-child(2)').textContent.trim();
                        listAddress.push(address);
                    });

                    $.ajax({
                        url: '@Url.Action("GetValueFromPlc")',
                        type: 'POST',
                        data: { address: listAddress },
                        success: function (response) {
                            updateTableValues(response);
                        },
                        error: function (xhr, status, error) {
                            console.error('Error fetching PLC values:', error)
                        }
                    });
                } catch (error) {
                    console.error('Error fetching PLC values:', error)
                }
            });

            //update a new value in tag
            $('.set-value-button').on('click', function () {
                var row = $(this).closest('tr');
                var id = row.find('td:eq(0)').text();
                var type = row.find('td:eq(3)').text();
                var value = row.find('.edit-value').val();

                if (type === "bool")
                    value = value === "1";

                var list = [{ Id: id, Type: type, Value: value }];

                $.ajax({
                    url: '@Url.Action("SetValueToPlc")',
                    type: 'POST',
                    data: { vmWrite: list },
                    success: function (response) {
                        window.location.href = '@Url.Action("TagList", "Management")';
                    },
                    error: function (xhr, status, error) {
                        window.location.href = '@Url.Action("TagList", "Management")';
                    }
                });
            });

            //Open tag Detail
            $('.details-button').on('click', function () {
                var row = $(this).closest('tr');
                var id = row.find('td:eq(0)').text();

                $.ajax({
                    url: '@Url.Action("EditTagInList")',
                    type: 'GET',
                    data: { idTag: id },
                    success: function (response) {
                        $('#detailsModal .modal-body').html(response);
                        $('#detailsModal').modal('show');
                    },
                    error: function (xhr, status, error) {
                        alert('Error');
                    }
                });
            });

            //Add Tag in List
            $('.add-button').on('click', function () {
                $.ajax({
                    url: '@Url.Action("AddTagInList")',
                    type: 'GET',
                    success: function (response) {
                        $('#detailsModal .modal-body').html(response);
                        $('#detailsModal').modal('show');
                    },
                    error: function (xhr, status, error) {
                        alert('Error');
                    }
                });
            });

            //Delete Tag in List
            $('.delete-button').on('click', function () {
                var row = $(this).closest('tr');
                var id = row.find('td:eq(0)').text();
                if (confirm(`Are you sure you want to delete this tag? \nIt will not be possible to reverse`)) {
                    $.ajax({
                        url: '@Url.Action("DeleteTagInList")',
                        type: 'Delete',
                        data: { id: id },
                        success: function (response) {
                            window.location.href = '@Url.Action("TagList", "Management")';
                        },
                        error: function (xhr, status, error) {
                            window.location.href = '@Url.Action("TagList", "Management")';
                        }
                    });
                }
            });

            function updateTableValues(data) {
                $('#plcTable tbody tr').each(function () {
                    var id = $(this).find('td:first').text().trim();
                    var plc = data.find(x => x.id == id);

                    if (plc) {
                        if (plc.type == 'bool') {
                            $(this).find('.edit-value').val(plc.value == 'true' ? 1 : 0);
                        } else if (plc.type == 'double') {
                            $(this).find('.edit-value').val(parseFloat(plc.value));
                        } else {
                            $(this).find('.edit-value').val(parseInt(plc.value, 10));
                        }
                    }
                });
            }
        });
    </script>
}

UI/Views/Management/_AddTagInListPartial.cshtml
@model Application.ViewModels.vmPlc

@{
    Layout = null;
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="AddTagInList" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group" hidden>
                    <label asp-for="Id" class="control-label"></label>
                    <input asp-for="Id" class="form-control" readonly />
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" required />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AddressPlc" class="control-label"></label>
                    <input asp-for="AddressPlc" class="form-control" required />
                    <span asp-validation-for="AddressPlc" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Type" class="control-label"></label>
                    <select asp-for="Type" class="form-select bg-light text-dark" id="Type"
                            asp-items="@(ViewBag.ListTypeTag as SelectList)"
                            aria-describedby="ListTypeTag">
                        <option selected disabled value="">Select one</option>
                    </select>
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
                <div class="form-group text-center mt-3">
                    <input type="submit" value="Save" class="btn btn-outline-success" />
                </div>
            </form>
        </div>
    </div>
</div>